config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'working_lists#index'

  resources :working_lists

  resources :charts

  resources :categories

  namespace :admin do
    resources :working_lists
  end

end

app/models/working_list.rb
# == Schema Information
#
# Table name: working_lists
#
#  id         :integer          not null, primary key
#  date       :date
#  department :string
#  colleague  :string
#  title      :string
#  is_plan    :boolean          default("t")
#  take_time  :float
#  descrption :text
#  progress   :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class WorkingList < ApplicationRecord

  belongs_to :user
  has_many :categories

  scope :recent, -> { order('created_at DESC') }
  scope :desc_date, -> { order('date DESC') }
  scope :desc_take_time, -> { order('take_time DESC') }
  scope :current_working_list, ->(current_user) { where("user_id = ?",current_user) }

end

app/controllers/admin/working_lists_controller.rb
class Admin::WorkingListsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :update, :edit, :destroy]
  before_action :require_is_admin

  layout "admin"

  def show
    @working_list = WorkingList.find(params[:id])
  end

  def index
    @working_lists = WorkingList.all
  end

  def new
    @working_list = WorkingList.new
  end

  def create
    @working_list = WorkingList.new(WorkingList_params)

    if @working_list.save
      redirect_to admin_WorkingLists_path
    else
      render :new
    end
  end

  def edit
    @working_list = WorkingList.find(params[:id])
  end

  def update
    @working_list = WorkingList.find(params[:id])
    if @working_list.update(WorkingList_params)
      redirect_to admin_WorkingLists_path
    else
      render :edit
    end
  end

  def destroy
    @working_list = WorkingList.find(params[:id])

    @working_list.destroy

    redirect_to admin_WorkingLists_path
  end

  private

  def WorkingList_params
    params.require( :working_list).permit(:category_name,:date, :department, :colleague, :title, :is_plan, :take_time, :descrption, :progress)
  end
end

app/controllers/working_lists_controller.rb
class WorkingListsController < ApplicationController
  before_action :authenticate_user! , only: [:new, :create, :edit, :destroy]

  def index
    @working_lists = case params[:working_list]
                      when 'by_date'
                        WorkingList.current_working_list(current_user).desc_date
                      when 'by_take_time'
                        WorkingList.current_working_list(current_user).desc_take_time
                      else
                        WorkingList.current_working_list(current_user).recent
                      end

    @today = Date.today
    @wl = @working_lists.where("date >= ? AND date <= ?",
                              @today.beginning_of_week,
                              @today.end_of_week)

    @wa = @wl.group(:category_name).sum(:take_time)
    @ws = @wl.sum(:take_time)

    @a = Array.new()

    @wa.values.each do |i|
      @a << i / @ws
    end

  end

  def new
    @working_list = WorkingList.new
  end

  def show
    @working_list = WorkingList.find(params[:id])
  end

  def edit
    @working_list = WorkingList.find(params[:id])
  end

  def update
    @working_list = WorkingList.find(params[:id])

    if @working_list.update(working_list_params)
      redirect_to working_lists_path, notice: "Update Success"
    else
      render :edit
    end
  end

  def destroy
    @working_list = WorkingList.find(params[:id])

    @working_list.destroy
    flash[:alert] = "WorkingList deleted"
    redirect_to working_lists_path
  end

  def create
    @working_list = WorkingList.new(working_list_params)
    @working_list.user = current_user

    if @working_list.save
      redirect_to working_lists_path
    else
      render :new
    end
  end

  private

  def find_workinglist_and_check_permission
    @working_list = WorkingList.find(params[:id])

    if current_user != @working_list.user
      redirect_to root_path, alert: "You have no permission."
    end
  end


  def working_list_params
    params.require( :working_list).permit(:category_name,:date, :department, :colleague, :title, :is_plan, :take_time, :descrption, :progress)
  end

end

app/helpers/admin/working_lists_helper.rb
module Admin::WorkingListsHelper
end

app/helpers/admin/workinglists_helper.rb
module Admin::WorkinglistsHelper
end

app/helpers/working_lists_helper.rb
module WorkingListsHelper
end

app/views/admin/working_lists/index.html.erb
<table class="table table-boldered">
  <% @working_lists.each do |wl| %>
  <tr>
    <td>
      <%= link_to(wl.title, admin_working_list_path(wl)) %>
    </td>
    <!-- <td>
      <%#= link_to("Edit", edit_admin_working_list_path(wl)) %>
      <%#= link_to("Destroy", admin_working_list_path(wl), :method => :delete, :data => { :confirm => "Are you sure?" }) %>
    </td> -->
    <td>
      <%= wl.created_at %>
    </td>
  </tr>
  <% end %>
</table>

app/views/admin/working_lists/show.html.erb
<div class="col-md-12">
  <h1>admin show</h1>
  <table class="table">
    <thead>
      <tr>
        <td>#</td>
        <td>Date</td>
        <td>Department</td>
        <td>Colleague</td>
        <td>Title</td>
        <td>is_plan</td>
        <td>Take Time</td>
        <td>Descrption</td>
        <td>Progress</td>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= @working_list.date %></td>
        <td><%= @working_list.department %></td>
        <td><%= @working_list.colleague %></td>
        <td><%= @working_list.title %></td>
        <td><%= @working_list.is_plan %></td>
        <td><%= @working_list.take_time %></td>
        <td><%= @working_list.descrption %></td>
        <td><%= @working_list.progress %></td>
      </tr>
    </tbody>
  </table>
</div>