config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'working_lists#index'

  resources :working_lists

  resources :charts

  resources :categories

  namespace :admin do
    resources :working_lists
  end

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :working_lists
  belongs_to :user
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    def index
      @categories = Category.where("user_id = ?",current_user)
    end

    def new
      @category = Category.new
    end

    def show
      @category = Category.find(params[:id])
    end

    def edit
      @category = Category.find(params[:id])
    end

    def update
      @category = Category.find(params[:id])

      if @category.update(category_params)
        redirect_to categories_path, notice: " category Update Success"
      else
        render :edit
      end
    end

    def destroy
      @category = Category.find(params[:id])

      @category.destroy
      flash[:alert] = "Category deleted"
      redirect_to categories_path
    end

    def create
      @category = Category.new(category_params)
      @category.user = current_user

      if @category.save
        redirect_to categories_path
      else
        render :new
      end
    end

    private

    def category_params
      params.require( :category).permit(:name)
    end

  end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/index.html.erb
<div class="col-md-4 col-md-offset-4">
    <h2>新增类别</h2>

    <hr>

    <div class="col-md-12">
      <div class="group">
        <%= link_to("New Work Category", new_category_path, class: "btn btn-danger pull-right") %>
      </div>
      <table class="table table-hover">
        <thead>
          <tr>
            <td>#</td>
            <td>work_category</td>
          </tr>
        </thead>
        <tbody>
          <% @categories.each do |category| %>
          <tr>
            <td><%=category.id%></td>
            <td><%=category.name%></td>
          </tr>
          <% end %>
      </table>
    </div>

</div>

app/views/categories/new.html.erb
<%= simple_form_for @category do |f| %>
  <div class="form-group">
    <%= f.input :name, input_html: { class: "form-control"} %>
  </div>
  <%= f.submit "Submit", class: "btn btn-primary", data: { disable_with: "Submitting..." } %>
<% end %>