config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'working_lists#index'

  resources :working_lists

  resources :charts

  resources :categories

  namespace :admin do
    resources :working_lists
  end

end

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">×</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
    <p class="text-center">Copyright ©2017 Working Register
        <br>Design by
        <a href="#" target=_new>hanhan</a>
    </p>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
          <a class="navbar-brand" href="/">Working Register</a>
          <%=link_to("生成图表",charts_path,class: "navbar-brand")%>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li>
                  <% if !current_user %>
                    <li><%= link_to("注册", new_user_registration_path) %></li>
                    <li><%= link_to("登入", new_user_session_path) %></li>
                  <% else %>
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        Hi!<%= current_user.email %>
                        <b class="caret"></b>
                      </a>
                      <ul class="dropdown-menu">
                        <li> <%= link_to("Admin Panel", admin_working_lists_path) %> </li>
                        <li> <%= link_to("登出", destroy_user_session_path, method: :delete) %> </li>
                      </ul>
                    </li>
                  <% end %>
                </li>
            </ul>
        </div>
    </div>
</nav>